### ISSUE TITLE
IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by lrkkevin** [Leeon123/CC-attack#109]
Exception in thread Thread-500:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "cc.py", line 234, in cc
    proxy = Choice(proxies).strip().split(":")
  File "/usr/lib64/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by Leeon123** [comment]
Do you really have the proxies list?
