### ISSUE TITLE
Bug errors on SLOW attack 

### ISSUE THREAD

**Issue by GhostRecon03** [Leeon123/CC-attack#17]
after reaching the thread of my set example i set a thread of 500

between 415 - 460 connections

Exception in thread Thread-345:ections: 455
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "cc.py", line 294, in slow
    s.send("X-a: {}\r\n".format(random.randint(1, 5000)).encode("utf-8"))
  File "/usr/lib/python3/dist-packages/socks.py", line 387, in send
    return _BaseSocket.send(self, bytes, flags, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

errors shows

**Comment by Leeon123** [comment]
Okay, let me fix it later.
