### ISSUE TITLE
When I raise threads to 1000, it come this error

### ISSUE THREAD

**Issue by yhl5555** [Leeon123/CC-attack#25]
Exception in thread Thread-1920:
Traceback (most recent call last):
  File "cc.py", line 213, in cc
    proxy = random.choice(proxies).strip().split(":")
  File "/usr/lib64/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "cc.py", line 240, in cc
    s.close()
UnboundLocalError: local variable 's' referenced before assignment

Exception in thread Thread-1921:
Traceback (most recent call last):
  File "cc.py", line 213, in cc
    proxy = random.choice(proxies).strip().split(":")
  File "/usr/lib64/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by Leeon123** [comment]
Looks like ur socks list have some spaces or others stuff. I'll update it as soon as possible.

**Comment by yhl5555** [comment]
Ok, Thank you for your help, and I found SSL attack can not work ,Hope you can update
---原始邮件---
发件人:"Leeon123"<notifications@github.com>
发送时间:2020年2月20日 星期四 上午0:6
收件人:"Leeon123/CC-attack"<CC-attack@noreply.github.com>
抄送:"yhl5555"<hx10@vip.qq.com>;"Author"<author@noreply.github.com>
主题:Re: [Leeon123/CC-attack] When I raise threads to 1000, it come thiserror (#25)

Looks like ur socks list have some spaces or others stuff. I'll update it as soon as possible.

&mdash;

**Comment by yhl5555** [comment]
Traceback (most recent call last):
  File "cc.py", line 699, in <module>
    main()#Coded by Leeon123
  File "cc.py", line 689, in main
    th.start()
  File "/usr/lib64/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Can you please have a look about this error when I raise the thread

**Comment by Leeon123** [comment]
That runtim eerror is because of your computer can't handle too much thread.

**Comment by Leeon123** [comment]
Updated

**Comment by jsd23** [comment]
Hi! I am new to this business. You can throw off video lessons how to do everything or write thanks in advance

**Comment by jsd23** [comment]
Hi! I am new to ddos. You can throw off video tutorials how to do everything or write thanks in advance
