### ISSUE TITLE
script is not working 

### ISSUE THREAD

**Issue by Chandram81** [Leeon123/CC-attack#30]
when I try to to attack, script is throwing an error

Exception in thread Thread-384:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "cc.py", line 230, in post
    proxy = Choice(proxies).strip().split(":")
  File "/usr/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
Exception in thread Thread-179:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "cc.py", line 230, in post
    proxy = Choice(proxies).strip().split(":")
  File "/usr/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by wzyonggege** [comment]
Cause your proxy list is empty.

**Comment by Chandram81** [comment]
> Cause your proxy list is empty.

Can I have list of Proxy and where do I need save it? Could you please help me on this?

**Comment by Chandram81** [comment]
I have updated proxy list, but sill same issue!

**Comment by Leeon123** [comment]
Cause your proxy list have empty lines, maybe will add a checker later.

**Comment by Chandram81** [comment]
Removed extra lines and it's working fine now! 

Noticed, It's not affecting on https domains
